CREATE TABLE IF NOT EXISTS service (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(3000),
    duration_in_min INT NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    deleted TINYINT DEFAULT 0 NOT NULL
);