CREATE TABLE IF NOT EXISTS role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(40) NOT NULL,
    login VARCHAR(20) DEFAULT NULL,
    password VARCHAR(256) NOT NULL,
    name varchar(30) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    phone_number VARCHAR(18) DEFAULT NULL,
    deleted TINYINT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id),
    FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(256) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(256) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);

INSERT INTO role VALUES
(1, "ROLE_CLIENT"),
(2, "ROLE_WORKER"),
(3, "ROLE_RECEPTIONIST"),
(4, "ROLE_ADMIN");