CREATE TABLE IF NOT EXISTS role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    email VARCHAR(40) NOT NULL,
    phone_number VARCHAR(11) DEFAULT NULL,
    login VARCHAR(20) DEFAULT NULL,
    password VARCHAR(256) NOT NULL,
    salt VARCHAR(30) DEFAULT NULL,
    deleted TINYINT NOT NULL,
    session_id VARCHAR(256) DEFAULT NULL,
    session_expire TIMESTAMP DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS user_roles (
    id_user INT NOT NULL,
    id_role INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES user (id),
    FOREIGN KEY (id_role) REFERENCES role (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;