CREATE TABLE IF NOT EXISTS role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    email VARCHAR(40) NOT NULL,
    phone_number VARCHAR(11) DEFAULT NULL,
    login VARCHAR(20) DEFAULT NULL,
    password VARCHAR(256) NOT NULL,
    salt VARCHAR(30) DEFAULT NULL,
    deleted TINYINT NOT NULL,
    session_id VARCHAR(256) DEFAULT NULL,
    session_expire TIMESTAMP DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS user_role (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id),
    FOREIGN KEY (role_id) REFERENCES role (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO role VALUES
(null, "ROLE_CLIENT"),
(null, "ROLE_WORKER"),
(null, "ROLE_RECEPTIONIST"),
(null, "ROLE_ADMIN");

INSERT INTO user VALUES
(1, "John", "Doe", "john.doe@gmail.com", "48123123123", "admin", "admin", null, 0, null, null);

INSERT INTO user_role VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4);