CREATE TABLE IF NOT EXISTS service (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(3000) NOT NULL,
    duration_in_min INT DEFAULT NULL,
    price FLOAT NOT NULL,
    deleted TINYINT DEFAULT 0 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;